name: CI
on:
  pull_request:
  push:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            java: 8
            jobtype: 1
          - os: ubuntu-latest
            java: 11
            jobtype: 1
    runs-on: ${{ matrix.os }}
    env:
      # define Java options for both official sbt and sbt-extras
      JAVA_OPTS: -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
      JVM_OPTS:  -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup
      uses: actions/setup-java@v4
      with:
        java-version: "${{ matrix.java }}"
        distribution: zulu
        cache: sbt
    - uses: sbt/setup-sbt@v1
    - name: Build and test
      run: |
        sbt -v scalafmtCheckAll
        sbt -v test
      shell: bash
